using System;
using System.Collections.Generic;
using UnityEngine;

namespace Systems.Lightweight_DI {
    public static class InjectionHandlerRegistry {
        private static readonly Dictionary<Type, IInjectionHandler> _handlers = new();
        private static bool _initialized = false;

        public static void RegisterHandler<T>(IInjectionHandler handler) {
            _handlers[typeof(T)] = handler;
        }

        public static void RegisterHandler(Type type, IInjectionHandler handler) {
            _handlers[type] = handler;
        }

        public static bool TryGetHandler(Type type, out IInjectionHandler handler) {
            return _handlers.TryGetValue(type, out handler);
        }

        public static void InjectDependencies(object target) {
            if (target == null) {
                Debug.LogWarning("Attempted to inject dependencies into null target");
                return;
            }

            Type targetType = target.GetType();
            
            if (_handlers.TryGetValue(targetType, out IInjectionHandler handler)) {
                handler.InjectDependencies(target);
            } else {
                Debug.LogWarning($"No injection handler found for type: {targetType.Name}");
            }
        }

        public static void Initialize() {
            if (_initialized) return;
            
            // Register handlers for known types
            RegisterKnownHandlers();
            _initialized = true;
        }

        private static void RegisterKnownHandlers() {
            // These will be auto-generated by the build process
            // For now, we'll register them manually as examples
        }
    }
} 